CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), status text NOT NULL DEFAULT 'PENDING', primary_email text UNIQUE, primary_phone text UNIQUE, locale text NOT NULL DEFAULT 'es-CO', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_profiles (user_id uuid PRIMARY KEY REFERENCES users(id), display_name text NOT NULL, birth_date date, avatar_ref text);
CREATE TABLE IF NOT EXISTS businesses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, status text NOT NULL DEFAULT 'DRAFT', verification_state text NOT NULL DEFAULT 'PENDING');
CREATE TABLE IF NOT EXISTS branches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), name text NOT NULL, status text NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE IF NOT EXISTS business_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, status text NOT NULL DEFAULT 'ACTIVE', UNIQUE (business_id,user_id,role));
CREATE TABLE IF NOT EXISTS membership_branch_scopes (membership_id uuid NOT NULL REFERENCES business_memberships(id), branch_id uuid NOT NULL REFERENCES branches(id), PRIMARY KEY (membership_id,branch_id));
CREATE TABLE IF NOT EXISTS credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), type text NOT NULL, public_reference text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'PENDING', issued_at timestamptz NOT NULL DEFAULT now(), blocked_at timestamptz, replaced_by_id uuid REFERENCES credentials(id));
CREATE TABLE IF NOT EXISTS terminals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), branch_id uuid NOT NULL REFERENCES branches(id), terminal_type text NOT NULL, status text NOT NULL DEFAULT 'PENDING', last_seen_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_type text NOT NULL, actor_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, correlation_id text NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
