CREATE TABLE IF NOT EXISTS categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, parent_id uuid REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), type text NOT NULL CHECK (type IN ('PRODUCT','SERVICE')), name text NOT NULL, description text, status text NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE IF NOT EXISTS product_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid NOT NULL REFERENCES products(id), sku text NOT NULL UNIQUE, attributes_json jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE IF NOT EXISTS prices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), variant_id uuid NOT NULL REFERENCES product_variants(id), branch_id uuid REFERENCES branches(id), amount_minor bigint NOT NULL CHECK (amount_minor > 0), currency char(3) NOT NULL DEFAULT 'COP', valid_from timestamptz NOT NULL DEFAULT now(), valid_to timestamptz);
CREATE TABLE IF NOT EXISTS sales (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES businesses(id), branch_id uuid NOT NULL REFERENCES branches(id), terminal_id uuid NOT NULL REFERENCES terminals(id), cashier_membership_id uuid NOT NULL REFERENCES business_memberships(id), customer_user_id uuid REFERENCES users(id), status text NOT NULL DEFAULT 'DRAFT', subtotal_minor bigint NOT NULL DEFAULT 0, total_minor bigint NOT NULL DEFAULT 0, currency char(3) NOT NULL DEFAULT 'COP', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sale_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sale_id uuid NOT NULL REFERENCES sales(id), variant_id uuid REFERENCES product_variants(id), description_snapshot text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0), unit_price_minor bigint NOT NULL CHECK (unit_price_minor > 0), total_minor bigint NOT NULL CHECK (total_minor > 0));
CREATE TABLE IF NOT EXISTS receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sale_id uuid NOT NULL UNIQUE REFERENCES sales(id), receipt_number text NOT NULL UNIQUE, type text NOT NULL DEFAULT 'VT', status text NOT NULL DEFAULT 'ISSUED', snapshot_json jsonb NOT NULL, issued_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cash_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sale_id uuid NOT NULL UNIQUE REFERENCES sales(id), amount_minor bigint NOT NULL CHECK (amount_minor > 0), currency char(3) NOT NULL DEFAULT 'COP', status text NOT NULL DEFAULT 'CAPTURED', recorded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS inventory_balances (variant_id uuid NOT NULL REFERENCES product_variants(id), branch_id uuid NOT NULL REFERENCES branches(id), quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (variant_id,branch_id));
